### ISSUE TITLE
Include link to iperf3 package in the installation instructions

### ISSUE THREAD

**Issue by nathantcampbell** [aredn/documentation#112]
Would it be possible to include the link to the iperf3 package in the installation instructions like the iperfspeed package is already linked. It was a bit of trouble to find the iperf3 package for a node that isn't part of a mesh yet and isn't internet linked.

The link I found was: http://downloads.arednmesh.org/snapshots/trunk/packages/mips_24kc/base/iperf3_3.7-1AREDN_mips_24kc.ipk

**Comment by ab7pa** [comment]
To avoid confusion we don't include all of the possible links to **iperf3** in the documentation because it is a standard AREDN package that your node will find at the correct location based on the specific firmware version it is running.  

It is best to let the node find its packages automatically because the package location depends on the firmware version running on the node (see examples below).  If you have nodes without access to http://downloads.arednmesh.org, then you can create a local software repository that all of your non-Internet connected nodes can use.  The documentation for how to accomplish this is in the **How To Guides** under "Creating a Local Package Server."  The **iperf3** package will be installed automatically as one of the _dependencies_ when you install the **iperfspeed** package, so you do not need to install it separately.  

If for some reason you want to install the **iperf3** package separately, the package location depends on the firmware version you are running.  If you run a _Stable Release_ then the correct package will be located in the "releases" tree (examples):  

- /releases/3/20/3.20.3.1/packages/mips_24kc/base/iperf3_3.7-1AREDN_mips_24kc.ipk 
- /releases/3/19/3.19.3.0/packages/mips_24kc/base/iperf3_3.5-1AREDN_mips_24kc.ipk 
- /releases/3/18/3.18.9.0/packages/mips_24kc/base/iperf3_3.5-1AREDN_mips_24kc.ipk 
- /releases/3/17/3.17.1.0RC1/ar71xx/generic/packages/base/iperf3_3.0.11-1_ar71xx.ipk 

If you are running a _Nightly Build_, only then will the correct package version be in the "snapshots" tree (example):  

- /snapshots/trunk/packages/mips_24kc/base/iperf3_3.7-1AREDN_mips_24kc.ipk
