### ISSUE TITLE
how to contribute legally?

### ISSUE THREAD

**Issue by kj7rrv** [aredn/documentation#123]
The ND license doesn't allow derivatives. How can contributions be made legally?

**Comment by ab7pa** [comment]
Sam KJ7RRV, good question...  The procedure for doc contributions is described here:
[https://github.com/aredn/documentation#contributing](https://github.com/aredn/documentation#contributing)

Anyone is welcome to submit contributions for consideration using the GitHub "Pull Request" process.  Once contributions are submitted, the AREDN® core team will evaluate the contribution and either approve/merge the item, request changes before approval, put the item on hold or deny the request.  _Amateur Radio Emergency Data Network, Inc._ holds the Creative Commons license and determines the overall content that goes into the doc set.  This seems like a good procedure since it provides a "living" document that can adapt to changes and updates in AREDN® features and functionality over time.

**Comment by kj7rrv** [comment]
Thank you! So it's okay to modify the docs for a contribution, but not eg to incorporate parts into another projects documentation?

**Comment by ab7pa** [comment]
Sam KJ7RRV, the answer above dealt with how to legally **_contribute_** new or updated material to the AREDN documentation.  How to legally **_share_** the licensed documentation is a different topic that is covered in the terms of the CC BY-NC-ND license itself.  The full text of that license is included in the AREDN documentation GitHub repository as well as in the Appendix section of the online docs.  You will also see the attribution or copyright information at the bottom of every page of the online documentation.  Here is a link to the license text that should clarify the conditions for sharing AREDN documentation (in whole or in part) as part of your project.
https://arednmesh.readthedocs.io/en/latest/LICENSE.html
